Array

In [10]:
import numpy as np

Value=[2, 4, 8, 10, 18, 20, 45, 64, 76, 81, 96, 100]

result = np.array(Value)

print(f"NumPy Array: {result}")
print(f"Type: {type(result)}")
print(f"Data Type: {result.dtype}")

NumPy Array: [  2   4   8  10  18  20  45  64  76  81  96 100]
Type: <class 'numpy.ndarray'>
Data Type: int64


user Input

In [9]:
import numpy as np
values = list(map(int, input("Enter numbers separated by space: ").split()))

result = np.array(values)

print(f"NumPy Array: {result}")
print(f"Type: {type(result)}")

NumPy Array: [ 4 94 29  8 34 16 18]
Type: <class 'numpy.ndarray'>


1-D Arrays

In [19]:
import numpy as np
Value=[2, 4, 8, 10, 18, 20, 45, 64, 76, 81, 96, 100]

result = np.array(Value)

print("One-Dimensional Array")
print(f"Result: {result}")
print(f"Array Dimensional: {result.ndim}D")
print(f"Array Shape: {result.shape}")

One-Dimensional Array
Result: [  2   4   8  10  18  20  45  64  76  81  96 100]
Array Dimensional: 1D
Array Shape: (12,)


2-D Arrays

In [22]:
import numpy as np
Value=[[2, 4, 8, 10, 18, 20], [45, 64, 76, 81, 96, 100]]

result = np.array(Value)

print("Two-Dimensional Array")
print(f"Result: \n{result}")
print(f"Array Dimensional: {result.ndim}D")
print(f"Array Shape: {result.shape}")

Two-Dimensional Array
Result: 
[[  2   4   8  10  18  20]
 [ 45  64  76  81  96 100]]
Array Dimensional: 2D
Array Shape: (2, 6)


3-D Arrays

In [21]:
import numpy as np
Value=[[2, 4, 8, 10], [18, 20, 45, 64], [76, 81, 96, 100]]

result = np.array(Value)

print("Three-Dimensional Array")
print(f"Result: \n{result}")
print(f"Array Dimensional: {result.ndim}D")
print(f"Array Shape: {result.shape}")

Three-Dimensional Array
Result: 
[[  2   4   8  10]
 [ 18  20  45  64]
 [ 76  81  96 100]]
Array Dimensional: 2D
Array Shape: (3, 4)


Multi-D Array

In [ ]:
import numpy as np
Value=[2, 4, 8, 10, 18, 20, 45, 64, 76, 81, 96, 100]

result = np.array(Value, ndmin=6)

print("Multi-Dimensional Array")
print(f"Result: \n{result}")
print(f"Array Dimensional: {result.ndim}D")

Multi-Dimensional Array
Result: 
[[[[[[  2   4   8  10  18  20  45  64  76  81  96 100]]]]]]
Array Dimensional: 6D
Array Shape: (1, 1, 1, 1, 1, 12)
