Zeros

In [ ]:
import numpy as np
Value = (4, 6)

result = np.zeros(Value, dtype=int)

print(f"Zeros Array: \n{result}")
print(f"Array Shape: {result.shape}")

Zeros Array: 
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Array Shape: (4, 6)


Ones

In [10]:
import numpy as np
Value = (4, 6)

result = np.ones(Value, dtype=int)

print(f"Ones Array: \n{result}")
print(f"Array Shape: {result.shape}")

Ones Array: 
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Array Shape: (4, 6)


Empty

In [9]:
import numpy as np
Value = (4, 6)

result = np.empty(Value, dtype=int)

print(f"Empty Array: \n{result}")
print(f"Array Shape: {result.shape}")

Empty Array: 
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Array Shape: (4, 6)


Range

In [14]:
import numpy as np
Value = (10+1)

result = np.arange(Value, dtype=int)

print(f"Range Array: \n{result}")
print(f"Array Shape: {result.shape}")

Range Array: 
[ 0  1  2  3  4  5  6  7  8  9 10]
Array Shape: (11,)


Diagonal

In [ ]:
import numpy as np
Value = (4, 6)

result = np.eye(*Value, dtype=int)

print(f"Diagonal Array: \n{result}")
print(f"Array Shape: {result.shape}")

Diagonal Array: 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]
Array Shape: (4, 6)


LinSpace

In [25]:
import numpy as np
result = np.linspace(4, 40, num=10)

print(f"LinSpace Array: \n{result}")
print(f"Array Shape: {result.shape}")

LinSpace Array: 
[ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40.]
Array Shape: (10,)
